spring.application.name=sgp-api-dto-exceptions

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/sgp-api-dto-exceptions-db
spring.datasource.username=root
spring.datasource.password=

api.security.token.secret=sgp-api-secret-key-dev-2026-arthur-cosmo
api.security.token.expiration=86400000

logging.level.org.springframework.security=TRACE